name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish
        run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
